REALtor1.2/Areas/Admin/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting.Internal;
using REALtor1._2.Data;
using REALtor1._2.Data.Models;
using Microsoft.AspNetCore.Hosting;
using REALtor1._2.Data.Interfaces;
using REALtor1._2.ViewModels;

namespace REALtor1._2.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class HouseController : Controller
    {
        private readonly DataManager dataManager;
        public HouseController(DataManager dataManager)
        {
            this.dataManager = dataManager;

        }
        public ViewResult ListHouses()
        {
            ViewBag.Title = "Поиск";
            HousesListViewModel houses = new HousesListViewModel();
            houses.getAllHouses = dataManager.Houses.Houses;
            return View(houses);
        }
        public ViewResult MainView()
        {
            ViewBag.Title = "Главная страница";
            return View();
        }

        [HttpPost]
        public ViewResult ListHousesFiltr(House filtrHouse)
        {
            HousesListViewModel houses = new HousesListViewModel();
            houses.getAllHouses = dataManager.Houses.Houses
                .Where(n => n.Available == true)
                .Where(n => n.CountOfRooms == filtrHouse.CountOfRooms)
                .Where(n => n.Square >= filtrHouse.Square)
                .Where(n => n.Price >= filtrHouse.Price)
                .Where(n => n.coldWater == true && filtrHouse.coldWater == true)
                .Where(n => n.hotWater == true && filtrHouse.hotWater == true)
                .Where(n => n.electricity == true && filtrHouse.electricity == true)
                .Where(n => n.gas == true && filtrHouse.gas == true)
                .Where(n => n.Area == filtrHouse.Area && n.Area != null)
                .Where(n => n.StatusOfHome == filtrHouse.StatusOfHome && n.StatusOfHome != null)
                .Select(n => n);
            return View(houses);
        }
        public ViewResult ListHousesFiltr()
        {
            return View();
        }
        public IActionResult Parametrs()
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            var entity = id == default ? new House() : dataManager.Houses.getObjectHouse(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(House model, IFormFile imgFile)
        {
            if (ModelState.IsValid)
            {
                dataManager.Houses.SaveHouse(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller",""));
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            dataManager.Houses.DeleteHouse(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller",""));
        }
    }
}

REALtor1.2/Areas/Admin/Views/House/Edit.cshtml
@model House
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}


<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="House" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="id" />
            <input type="hidden" asp-for="Available" value="true" />

            <div asp-validation-summary="All"></div>
            <div class="box">
                <label asp-for="Name">Заголовок:</label>
                <input asp-for="Name" size="60" />
                <span asp-validation-for="Name"></span>
            </div>
            <div class="box">
                <label asp-for="Address">Адрес:</label>
                <input asp-for="Address" size="60" />
                <span asp-validation-for="Address"></span>
            </div>
            <div class="box">
                <label asp-for="CountOfRooms">Количество комнат</label>
                <input asp-for="CountOfRooms" size="20" />
                <span asp-validation-for="CountOfRooms"></span>
            </div>
            <div class="box">
                <label asp-for="Price">Цена:</label>
                <input asp-for="Price" size="70" />
                <span asp-validation-for="Price"></span>
            </div>
            <div class="box">
                <label asp-for="Square">Площадь:</label>
                <input asp-for="Square" size="60" />
                <span asp-validation-for="Square"></span>
            </div>
            <div class="box">
                <label asp-for="Area">Район:</label>
                <input asp-for="Area" size="60" />
                <span asp-validation-for="Area"></span>
            </div>
            <div class="box">
                <label asp-for="coldWater">Холодная вода</label>
                <input asp-for="coldWater" value="true" type="checkbox" />
                <label asp-for="hotWater">Горячая вода</label>
                <input asp-for="hotWater" value="true" type="checkbox" />
                <label asp-for="electricity">Электричество</label>
                <input asp-for="electricity" value="true" type="checkbox" />
                <label asp-for="gas">Газ</label>
                <input asp-for="gas" value="true" type="checkbox" />
            </div>
            <div class="box">
                <label asp-for="StatusOfHome">Частный дом</label>
                <input asp-for="StatusOfHome" value="Частный дом" type="radio" />

                <label asp-for="StatusOfHome">Новостройка</label>
                <input asp-for="StatusOfHome" value="Новостройка" type="radio" />

                <label asp-for="StatusOfHome">Старый многоэтажный дом</label>
                <input asp-for="StatusOfHome" value="Старый многоэтажный дом" type="radio" />

                <label asp-for="StatusOfHome">Гараж</label>
                <input asp-for="StatusOfHome" value="Гараж" type="radio" />

                <label asp-for="StatusOfHome">Старый ветхий дом</label>
                <input asp-for="StatusOfHome" value="Старый ветхий дом" type="radio" />
            </div>
            <div class="box">
                <label asp-for="Seller">ФИО владельца</label>
                <input asp-for="Seller.Fio" size="60" />
            </div>
            <div class="box">
                <label asp-for="Img">Фото дома:</label>
                <input asp-for="Img" size="60" />
                <span asp-validation-for="Img"></span>
            </div>

            <div class="box">
                <label asp-for="Despription">Описание:</label>
                <input asp-for="Despription" size="100" />
                <span asp-validation-for="Despription"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>

REALtor1.2/Areas/Admin/Views/House/ListHouses.cshtml
@{
    <div class="open-popup">
        <a href="/Admin/House/Parametrs" id="open-popup">Параметры</a>
    </div>
    foreach (var house in Model.getAllHouses)
    {
<div class="list">
    <img src="@house.Img" alt="@house.Name">
    <h3>@house.Name</h3>
    <p>@house.Price рублей </p>
    <p> Площадь:@house.Square </p>
    <p>Количество комнат: @house.CountOfRooms</p>
    <p>@house.StatusOfHome</p>
    <p> Район:@house.Area </p>
    <p> Адрес:@house.Address</p>
    <p> Условия жизни: </p>
    <p> @{ if (house.coldWater == true)} Холодная вода </p>
    <p> @{ if (house.hotWater == true)} Горячая вода </p>
    <p> @{ if (house.electricity == true)} Электричество </p>
    <p> @{ if (house.gas == true)} Газ </p>
    <p>@house.Despription</p>

</div>
    }
}

REALtor1.2/Areas/Admin/Views/House/ListHousesFiltr.cshtml
@{
    <div class="open-popup">
        <a href="?Admin/House/Parametrs" id="open-popup">Параметры</a>
    </div>
    foreach (var house in Model.getAllHouses)
    {
        <div class="list">
            <img src="@house.Img" alt="@house.Name">
            <h3>@house.Name</h3>
            <p>@house.Price рублей </p>
            <p> Площадь:@house.Square </p>
            <p>Количество комнат: @house.CountOfRooms</p>
            <p>@house.StatusOfHome</p>
            <p> Район:@house.Area </p>
            <p> Адрес:@house.Address</p>
            <p> Условия жизни: </p>
            <p> @{ if (house.coldWater == true)} Холодная вода </p>
            <p> @{ if (house.hotWater == true)} Горячая вода </p>
            <p> @{ if (house.electricity == true)} Электричество </p>
            <p> @{ if (house.gas == true)} Газ </p>
            <p>@house.Despription</p>

        </div>
    }
}

REALtor1.2/Areas/Admin/Views/House/MainView.cshtml
<img src="https://clipart-best.com/img/house/house-clip-art-69.png" width="96%"
     height="100%" alt="">

REALtor1.2/Areas/Admin/Views/House/Parametrs.cshtml
@model House
@{
    <div class="popup" id="popup">
        <div class="popup-container">
            <div class="popup-body">
                <div class="close-popup">
                    <a href="/Admin/Houses/ListHouses" id="close-popup">X</a>
                </div>
                <h1 id="paramsHeading">Параметры</h1>
                <form action="/Houses/ListHousesFiltr" method="post">
                    <p class="paramsText">Площадь недвижимости:</p>
                    <p class="paramsText">от<input asp-for="@Model.Square" type="number" required autofocus>кв.м.</p>
                    <p class="paramsText">Количество комнат:</p>
                    <input asp-for="@Model.CountOfRooms" type="number" required>
                    <p class="paramsText">Цена:</p>
                    <p class="paramsText">от<input asp-for="@Model.Price" type="number" step="1000" required>рублей</p>
                    <p class="paramsText">Район:</p>
                    <p class="paramsText">Индустриальный<input asp-for="@Model.Area" value="Индустриальный" type="radio">Ленинский<input asp-for="@Model.Area" value="Ленинский" type="radio">Октябрьский<input asp-for="@Model.Area" value="Октябрьский" type="radio"></p>
                    <p class="paramsText">Устиновский<input asp-for="@Model.Area" value="Устиновский" type="radio">Первомайский<input asp-for="@Model.Area" value="Первомайский" type="radio"></p>
                    <p class="paramsText">Вид недвижимости:</p>
                    <p class="paramsText">Гараж<input asp-for="@Model.StatusOfHome" value="Гараж" type="radio">Новостройка<input asp-for="@Model.StatusOfHome" value="Новостройка" type="radio">Старый ветхий дом<input asp-for="@Model.StatusOfHome" value="Старый ветхий дом" type="radio"></p>
                    <p class="paramsText">Частный дом<input asp-for="@Model.StatusOfHome" value="Частный дом" type="radio">Старый многоэтажный дом<input asp-for="@Model.StatusOfHome" value="Старый многоэтажный дом" type="radio"></p>
                    <p class="paramsText">Условия жизни:</p>
                    <p class="paramsText">Холодная вода<input asp-for="@Model.coldWater" value="true" type="checkbox">Горячая<input asp-for="@Model.hotWater" value="true" type="checkbox">Электричество<input asp-for="@Model.electricity" value="true" type="checkbox"></p>
                    <p class="paramsText">Газ<input asp-for="@Model.gas" value="true" type="checkbox"></p>
                    <input type="submit" value="ГОТОВО">
                </form>
            </div>
        </div>
    </div>
    <script src="~/js/jsScript.js"></script>
}